2022-11-26 11:52:40,470 ERROR: Exception on /removebookmark/14 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 228, in removebookmark
    db.session.delete(b)
  File "<string>", line 2, in delete
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2707, in delete
    self._delete_impl(state, instance, head=True)
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2713, in _delete_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Instance '<Bookmark at 0x7faf895a6320>' is not persisted
2022-11-26 11:53:57,074 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
2022-11-26 11:54:02,278 ERROR: Exception on /removebookmark/14 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 228, in removebookmark
    db.session.delete(b)
  File "<string>", line 2, in delete
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2707, in delete
    self._delete_impl(state, instance, head=True)
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2713, in _delete_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Instance '<Bookmark at 0x7fd37cff9570>' is not persisted
2022-11-26 11:54:43,246 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
2022-11-26 11:54:45,715 ERROR: Exception on /removebookmark/14 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 228, in removebookmark
    db.session.delete(b)
  File "<string>", line 2, in delete
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2707, in delete
    self._delete_impl(state, instance, head=True)
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2713, in _delete_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Instance '<Bookmark at 0x7f9814ded570>' is not persisted
2022-11-26 11:56:05,871 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
2022-11-26 11:56:07,794 ERROR: Exception on /removebookmark/14 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 228, in removebookmark
    db.session.delete(b)
  File "<string>", line 2, in delete
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2707, in delete
    self._delete_impl(state, instance, head=True)
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2713, in _delete_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Instance '<Bookmark at 0x7f98cbcf5570>' is not persisted
2022-11-26 11:58:21,870 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
2022-11-26 11:58:25,864 ERROR: Exception on /removebookmark/14 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 228, in removebookmark
    db.session.delete(b)
  File "<string>", line 2, in delete
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2707, in delete
    self._delete_impl(state, instance, head=True)
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2713, in _delete_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Instance '<Bookmark at 0x7f7a72dd1570>' is not persisted
2022-11-26 11:59:16,222 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
2022-11-26 11:59:20,096 ERROR: Exception on /removebookmark/14 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 228, in removebookmark
    db.session.delete(b)
  File "<string>", line 2, in delete
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2707, in delete
    self._delete_impl(state, instance, head=True)
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2713, in _delete_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Instance '<Bookmark at 0x7f033c1f9570>' is not persisted
