2022-11-26 11:40:49,380 ERROR: Exception on /removebookmark/14 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 229, in removebookmark
    db.session.delete(removebookmark)
  File "<string>", line 2, in delete
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2707, in delete
    self._delete_impl(state, instance, head=True)
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2713, in _delete_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Instance '<Bookmark at 0x7fbd2f32ec50>' is not persisted
2022-11-26 11:41:36,059 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
2022-11-26 11:41:47,676 ERROR: Exception on /removebookmark/14 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 229, in removebookmark
    db.session.delete(removebookmark)
  File "<string>", line 2, in delete
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2707, in delete
    self._delete_impl(state, instance, head=True)
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2713, in _delete_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Instance '<Bookmark at 0x7fe39b3dda50>' is not persisted
2022-11-26 11:46:34,055 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
2022-11-26 11:46:52,907 ERROR: Exception on /removebookmark/14 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 229, in removebookmark
    db.session.delete(removebookmark)
  File "<string>", line 2, in delete
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2707, in delete
    self._delete_impl(state, instance, head=True)
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2713, in _delete_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Instance '<Bookmark at 0x7f09ae733a00>' is not persisted
2022-11-26 11:48:20,830 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
2022-11-26 11:48:23,023 ERROR: Exception on /removebookmark/14 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 227, in removebookmark
    removebookmark = Bookmark(user_id=current_user.id, activity_id=activityid).first()
AttributeError: 'Bookmark' object has no attribute 'first'
2022-11-26 11:52:04,873 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
2022-11-26 11:52:07,261 ERROR: Exception on /removebookmark/14 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 228, in removebookmark
    db.session.delete(removebookmark)
  File "<string>", line 2, in delete
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2707, in delete
    self._delete_impl(state, instance, head=True)
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2713, in _delete_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Instance '<Bookmark at 0x7f497bae5570>' is not persisted
2022-11-26 11:52:37,370 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
2022-11-26 11:52:39,366 ERROR: Exception on /removebookmark/14 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 228, in removebookmark
    db.session.delete(b)
  File "<string>", line 2, in delete
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2707, in delete
    self._delete_impl(state, instance, head=True)
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2713, in _delete_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Instance '<Bookmark at 0x7faf89ded570>' is not persisted
